### ISSUE TITLE
Introduce clippy into CI pipeline 

### ISSUE THREAD

**Issue by ascjones** [paritytech/jsonrpc#396] opened 2019-02-25 14:49 UTC
Suggested by @kirushik in #395. We would need to use a `.clippy.toml` file to whitelist the lints we care about.

**Comment by kirushik** [comment] 2019-02-25 14:49
It should be really straighforward to add: https://github.com/rust-lang/rust-clippy#travis-ci

**Comment by ascjones** [comment] 2019-02-25 14:50
@kirushik be my guest :smile:

**Comment by dvc94ch** [comment] 2019-07-02 19:20
Closing as duplicate of #418

**Closed by dvc94ch** 2019-07-02 19:20 UTC
