### ISSUE TITLE
Remove Stack from Error Response

### ISSUE THREAD

**Issue by fredfortier** [paritytech/jsonrpc#449] opened 2019-07-11 02:03 UTC
My program is handling application errors by raising `jsonrpc_core::Error`. For illustration, it might look like this:
```rust
        io.add_method(TEST, move |params: Params| {
            if (is_error) {
                return Err(ServerError {
                    code: ErrorCode::MyError,
                     message: format!("This is a well-known error, no need for the stack trace."),
                     data: None,
                });
            }
            Ok(body)
        });
```
Returning the error code is sufficient for most application errors. However, all error responses seem to include a stack trace by default. Is it possible to remove the stack?

**Comment by tomusdrw** [comment] 2019-07-12 10:08
Where exactly is the stack trace displayed? Is it because you are printing the error? `jsonrpc_core::Error` is only implementing `std::error::Error` but I don't think it affects the way it's displayed or debug-printed.

Can you provide a minimal example to reproduce the issue? Looking at the linked issue in `enigma` repo it seems that it might be some other error that get's printed out in the jsonrpc method handler, not the sjonrpc error itself.

**Comment by tomusdrw** [comment] 2020-07-27 07:47
Closing. Please reopen if you feel this is a bug in that repo.

**Closed by tomusdrw** 2020-07-27 07:47 UTC
Labels: invalid
